### ISSUE TITLE
English version of Readme.md

### ISSUE THREAD

**Issue by vafjr87** [what-studio/tossi#2]
안녕하십니까, @what-studio!

I'm a Brazilian learner of Korean and I think of some projects about hangul and Korean. I already developed a script (based in @sublee korean packge) that romanizes Hangul to Latin script. I think have some interest in this project, but I can't read it. Could you translate the Readme.me to English as a big favor?

고맙습니다!

**Comment by sublee** [comment]
Thank you for your interest.  I've started to translate the README in English at [README.en.md](https://github.com/what-studio/tossi/blob/master/README.en.md).

**Comment by sublee** [comment]
I finished to write.  I'm not a native English speaker so there can be mistakes.  Please review it.

**Comment by vafjr87** [comment]
Really, really, really thank you, @sublee! You're reply was really fast! I reviewed the English version and it's awesome. It just needs 2 small corrections in the word "natrual". It should be "natural". 

You made a nice work!

Thanks and greetings from Brazil 🇧🇷

**Comment by sublee** [comment]
Oh, I fixed that typo.  Thank you for your detail review.  I close this issue.
