### ISSUE TITLE
조사 추정 실패시 허용하지 않고 오류를 내는 intolerant 모드를 추가하고자 합니다

### ISSUE THREAD

**Issue by youknowone** [what-studio/tossi#3]
조사 추정에 실패할 경우 오류를 잡아내서 다른 방식으로 처리하려고 합니다.

몇가지 방법을 생각하고 있는데, 적절한 방법을 골라주시거나 제안해주시면 좋겠습니다.

1. 추정 실패시 오류를 내는 `guess_coda`를 만드는 방법
라이브러리를 건드리지 않고 필요한 기능을 구현할수 있습니다.

2. tolerance_style에 `None` 또는 `INTOLERANT_STYLE`을 추가하는 방법
조사 추정에 실패하면 오류를 내는 기능을 tossi에 추가합니다.

3. tolerance_style에 조사 외에 임의의 문자열을 넣을수 있도록 추가하는 방법
ex: `{item을} 착용했습니다` + tolerance style ` 아이템을`
- 무기 => `무기를 착용했습니다`
- 신발 => `신발을 착용했습니다`
- Blade => `Blade 아이템을 착용했습니다`

원하는 동작은 3번인데요. 3 또는 2의 동작을 패치로 받아 들일 수 있으면 해당기능을 구현해서 패치로 제출하고 그렇지 않다면 1처럼 해서 우회적으로 구현하려고 합니다.

의견 부탁드립니다.

**Comment by sublee** [comment]
3번이 좋아보입니다. API를 어떻게 제공할지 먼저 제안해주실래요?

**Comment by youknowone** [comment]
```
tossi.postfix_particle(u'Blade', u'을', tolerance_style=CustomStyle(' 아이템을'))  # tolerance_style만 고치는 경우
tossi.postfix_particle(u'Blade', u'을', tolerance_style=' 아이템을')  # string 이 들어오면 자동으로 custom style 로 인식하는 경우
tossi.postfix_particle(u'Blade', u'을', tolerance_style=None, default=' 아이템을')  # tolerance_style은 그대로 두고 기본값 추가
tossi.postfix_particle(u'Blade', u'을', u' 아이템을')  # 세번째 파라미터를 default 인자로 취급 (dict.get 처럼)
```

어떤게 좋아 보이나요? 
저는 마지막처럼 쓰는걸 선호하는데 기존 API와 충돌이 있을까 싶네요.

그렇지 않다면 CustomStyle을 구현하고 2번을 지원하는게 좋을것 같습니다.
이 형태가 Style로 취급될만한 이유는,

```python
tossi.postfix_particle(u'Blade', u'을', tolerance_style=u'을/를')
```
과 같이 사용자 입장에서는 임의의 형식을 바로 문자열로 지정할 수 있는것이 합리적인 API 호출 방법처럼 보이기 때문이고요. 

제가 쓴 사례는 '을/를'을 쓰는 것의 상당히 특수한 사례 정도로 볼수 있을것 같습니다.

**Comment by sublee** [comment]
저는 `CustomStyle` 없이 2번이 좋아보입니다. `tolerance_style`이 `int`거나 `str`이도록이요.

**Comment by youknowone** [comment]
말씀대로 만들어 보았습니다. PR #4 에 등록하였습니다. 이 이슈는 닫고 수정할 내용이 있으면 PR에서 이어가도 되겠지요?

**Comment by sublee** [comment]
PR과 함께 닫을게요. 우선 다시 열겠습니다.

**Comment by sublee** [comment]
#4로 해결됨.
